apiVersion: v1
kind: Service
metadata:
  name: glvd-database
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: database
spec:
  selector:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: database
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
      targetPort: postgres
  type: ClusterIP
  clusterIP: None
---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: database
stringData:
  username: glvd
  password: change-me-i-am-not-secure123
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: glvd-database
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: database
spec:
  replicas: 1
  serviceName: "glvd-database"
  selector:
    matchLabels:
      app.kubernetes.io/name: glvd
      gardenlinux.io/glvd-component: database
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glvd
        gardenlinux.io/glvd-component: database
    spec:
      containers:
      - image: ghcr.io/gardenlinux/glvd-postgres:edgefulldata
        name: glvd-postgres
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        ports:
          - containerPort: 5432
            protocol: TCP
            name: postgres
        env:
          - name: POSTGRES_DATABASE
            value: glvd
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: POSTGRES_HOST
            value: glvd-postgres
          - name: POSTGRES_PORT
            value: "5432"
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 5Gi
      storageClassName: 'default'
