kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: glvd
  name: glvd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "glvd"
  strategy: {}
  template:
    metadata:
      labels:
        app: glvd
    spec:
      containers:
        - image: ghcr.io/gardenlinux/glvd-api:edge_bare
          name: glvd-api
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          env:
            # cf https://github.com/spring-projects/spring-lifecycle-smoke-tests/tree/main/data/data-jpa#prevent-early-database-interaction
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/glvd"
            - name: SPRING_DATASOURCE_USERNAME
              value: glvd
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: SPRING_JPA_DATABASEPLATFORM
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_BOOT_ALLOW_JDBC_METADATA_ACCESS
              value: "false"
            - name: SPRING_JPA_HIBERNATE_DDLAUTO
              value: "none"
            - name: SPRING_SQL_INIT_MODE
              value: "never"
        - image: ghcr.io/gardenlinux/glvd-postgres:edgenotls
          name: glvd-postgres
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          ports:
            - containerPort: 5432
              hostPort: 5432
          env:
            - name: POSTGRES_USER
              value: glvd
            - name: POSTGRES_DATABASE
              value: glvd
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: POSTGRES_HOST
              value: glvd-postgres
            - name: POSTGRES_PORT
              value: "5432"
        # TODO: data-ingestion should be running as a cron job
        - name: data-ingestion
          image: ghcr.io/gardenlinux/glvd:edge
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
          command:
            - /bin/bash
            - -c
            - sleep 5 && echo start && /usr/local/src/ingest-postgres.sh && echo done && sleep infinity
          env:
            - name: PGUSER
              value: glvd
            - name: PGDATABASE
              value: glvd
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-password
                  key: password
            - name: PGHOST
              value: localhost
            - name: PGPORT
              value: "5432"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: glvd
  name: glvd
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: glvd
  type: LoadBalancer
