apiVersion: v1
kind: ConfigMap
metadata:
  name: glvd-ingestion
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: glvd-ingestion
data:
  databaseName: glvd
  databaseHost: glvd-database-0.glvd-database
  databasePort: "5432"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: glvd-ingestion
  labels:
    app.kubernetes.io/name: glvd
    gardenlinux.io/glvd-component: glvd-ingestion
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: glvd
        gardenlinux.io/glvd-component: glvd-ingestion
    spec:
      restartPolicy: OnFailure
      containers:
      - name: data-ingestion
        image: ghcr.io/gardenlinux/glvd:edge
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
          limits:
            cpu: "2"
            memory: "4Gi"
        command:
          - /bin/bash
          - -c
          - sleep 5 && echo start && /usr/local/src/ingest-postgres.sh && echo done && sleep infinity
        env:
          - name: PGDATABASE
            valueFrom:
              configMapKeyRef:
                name: glvd-ingestion
                key: databaseName
          - name: PGUSER
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: username
          - name: PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-credentials
                key: password
          - name: PGHOST
            valueFrom:
              configMapKeyRef:
                name: glvd-ingestion
                key: databaseHost
          - name: PGPORT
            valueFrom:
              configMapKeyRef:
                name: glvd-ingestion
                key: databasePort
