apiVersion: batch/v1
kind: CronJob
metadata:
  name: glvd-data-ingestion
spec:
  jobTemplate:
    metadata:
      name: glvd-data-ingestion
    spec:
      template:
        spec:
          containers:
          - command:
            - /usr/local/src/ingest-postgres.sh
            image: {{ .Values.ingestion.image.repository }}
            imagePullPolicy: {{ .Values.ingestion.image.pullPolicy }}
            name: glvd-data-ingestion
            resources: {}
            env:
              - name: PGUSER
                value: {{ .Values.ingestion.database.username }}
              - name: PGDATABASE
                value: {{ .Values.ingestion.database.databaseName }}
              - name: PGPASSWORD
                valueFrom:
                  secretKeyRef:
                    name: glvd-creds
                    key: password
              - name: PGHOST
                value: glvd-database-0.glvd-database  # FIXME: build this with a helper
              - name: PGPORT
                value: "5432"
          restartPolicy: OnFailure
  schedule: '0 11 * * *'
  timeZone: 'Europe/Berlin'
