apiVersion: v1
kind: Service
metadata:
  name: glvd
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: glvd
    helm.sh/chart: glvd
    app.kubernetes.io/instance: {{ .Release.Name }}
    gardenlinux.io/glvd-component: tracker
spec:
  selector:
    app.kubernetes.io/name: glvd
    helm.sh/chart: glvd
    app.kubernetes.io/instance: {{ .Release.Name }}
    gardenlinux.io/glvd-component: tracker
  ports:
  - port: {{ .Values.loadbalancerPort }}
    protocol: TCP
    targetPort: glvd-api
  type: ClusterIP
