services:
  glvd:
    build:
      dockerfile: Containerfile
  glvd-postgres:
    image: ghcr.io/gardenlinux/glvd-postgres:edge
    environment:
      POSTGRES_USER: glvd
      POSTGRES_DB: glvd
      POSTGRES_PASSWORD: glvd
    expose:
      - 5432
