FROM debian:trixie

# XXX: Debian Experimental required for python3-sqlalchemy (>= 2)
RUN sed -i -e 's/Suites: trixie trixie-updates/\0 experimental/' /etc/apt/sources.list.d/debian.sources
RUN apt-get update && \
    apt-get upgrade -y --no-install-recommends git python3-asyncpg python3-hypercorn python3-pip python3-poetry-core python3-quart python3-requests python3-sqlalchemy/experimental

RUN groupadd --gid 1000 dev \
    && useradd --uid 1000 --gid 1000 --shell /bin/bash --create-home dev
USER dev
WORKDIR /home/dev
