name: CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup Node.js
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
      with:
        node-version: '24'

    - name: Install Bruno CLI
      run: npm install -g @usebruno/cli

    - name: Compose Up
      run: |
        docker compose --file deployment/compose/compose.yaml up --detach

    - name: Wait for GLVD to be up
      run: |
        # Wait for HTTP 200 and status: UP in response body
        until [ "$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8080/actuator/health)" = "200" ] && \
              [ "$(curl -s http://localhost:8080/actuator/health | jq -r .status)" = "UP" ]; do
          sleep 1
        done

    - run: docker ps

    - name: Run API Tests
      run: bru run --env ci --reporter-html results.html
      working-directory: api-tests

    - name: Upload Test Results
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: test-results
        path: api-tests/results.html
